const nome = "Edson"
console.log(nome.charAt(3))
console.log(nome.charCodeAt(3))
console.log(nome.replace("so", "XX"))
console.log(nome.length)
console.log(nome.endsWith("n"))
console.log(nome.indexOf("d"))
console.log(nome.substring(0, 3))
console.log(nome.toLocaleUpperCase())
console.log("Ana,Maria,José".split(","))
console.log(nome.concat(' Martin '.concat('Feitosa')))